// Dictionnaires d'affichage. Le texte français sert de clé : une entrée
// manquante retombe sur le français plutôt que de casser l'écran.
//
// Attention : les valeurs du fichier de réponses (« oui », « conventionné »,
// « avec supplément »…) sont traduites POUR L'AFFICHAGE seulement. Ce qui est
// enregistré et exporté reste le français attendu par Test-Achats.

const NL = {
  /* --- valeurs du fichier de réponses (affichage seulement) --- */
  oui: "ja",
  non: "nee",
  conventionné: "geconventioneerd",
  "partiellement conventionné": "gedeeltelijk geconventioneerd",
  "non conventionné": "niet-geconventioneerd",
  "avec supplément": "met supplement",
  "sans supplément": "zonder supplement",
  "la personne au téléphone ne le savait pas": "de persoon aan de telefoon wist het niet",
  "ne s'applique pas": "niet van toepassing",
  "je n'ai pas reçu de l'information à ce sujet": "ik heb daarover geen informatie gekregen",
  remboursé: "terugbetaald",
  "non remboursé": "niet terugbetaald",
  "pas de nouveaux patients": "geen nieuwe patiënten",
  retraite: "pensioen",
  autres: "andere",

  /* --- colonnes du fichier de réponses --- */
  "Province de l'adresse du dentiste": "Provincie van het adres van de tandarts",
  Dentiste: "Tandarts",
  "Statut Inami": "Riziv-statuut",
  "Date de l'appel": "Datum van de oproep",
  "Nr de téléphone": "Telefoonnummer",
  "Le dentiste s'est renseigné sur le droit à l'intervention majorée ?":
    "Informeerde de tandarts naar het recht op de verhoogde tegemoetkoming?",
  "Le dentiste a demandé votre numéro de registre national ?": "Vroeg de tandarts uw rijksregisternummer?",
  "Rendez-vous possible ?": "Afspraak mogelijk?",
  "Si pas de rendez-vous : raison": "Als geen afspraak: reden",
  "Orienté vers un autre dentiste de la même pratique de groupe":
    "Doorverwezen naar een andere tandarts van dezelfde groepspraktijk",
  "Orienté vers un dentiste d'un autre cabinet": "Doorverwezen naar een tandarts van een andere praktijk",
  "Date du premier rendez-vous proposé": "Datum van de eerste voorgestelde afspraak",
  "Ce premier rendez-vous est…": "Die eerste afspraak is…",
  "Informations reçues sur le prix de la consultation ?": "Informatie gekregen over de prijs van de consultatie?",
  "Prix du premier rendez-vous": "Prijs van de eerste afspraak",
  "Rendez-vous possible sans supplément ?": "Afspraak mogelijk zonder supplement?",
  "Date du rendez-vous sans supplément": "Datum van de afspraak zonder supplement",
  "Ce rendez-vous a-t-il lieu dans le même cabinet ?": "Gaat die afspraak door in dezelfde praktijk?",
  "Adresse du rendez-vous sans supplément": "Adres waar de afspraak zonder supplement doorgaat",
  "Une consultation chez un hygiéniste a-t-elle été proposée ?": "Werd een consultatie bij een mondhygiënist voorgesteld?",
  "Informations reçues sur le remboursement de l'hygiéniste ?":
    "Informatie gekregen over de terugbetaling van de mondhygiënist?",
  "Cette consultation est…": "Die consultatie is…",
  Remarques: "Opmerkingen",

  /* --- navigation --- */
  "Appels dentistes": "Tandartsoproepen",
  "Mystery shopping · Test-Achats": "Mystery shopping · Testaankoop",
  Liste: "Lijst",
  Appel: "Oproep",
  Journée: "Dag",
  Suivi: "Opvolging",
  Données: "Gegevens",
  "Qui reste à appeler": "Wie nog te bellen valt",
  "Encoder l'appel en cours": "De lopende oproep coderen",
  "Ce qui est déjà encodé": "Wat al gecodeerd is",
  "Rappels et annulations": "Terugbellen en annuleren",
  "Import, Excel, sauvegarde": "Import, Excel, back-up",
  Langue: "Taal",
  "Chargement…": "Laden…",
  Fermer: "Sluiten",
  Annuler: "Annuleren",
  Modifier: "Wijzigen",
  Replier: "Inklappen",
  Supprimer: "Verwijderen",
  Encoder: "Coderen",
  Revoir: "Bekijken",
  "Revoir l'appel": "Oproep bekijken",
  "Plus d'options": "Meer opties",
  Scénario: "Scenario",
  "Scénario de la mission": "Scenario van de opdracht",
  "Raccourcis clavier": "Sneltoetsen",
  "Les réponses partent en français dans le fichier Excel, quelle que soit la langue choisie.":
    "De antwoorden gaan altijd in het Frans naar het Excel-bestand, welke taal u ook kiest.",

  /* --- liste d'appel --- */
  "{faits} / {total} appelés": "{faits} / {total} gebeld",
  "{n} restants": "nog {n}",
  "{n} à appeler": "{n} te bellen",
  "Appeler le suivant : {nom}": "Volgende bellen: {nom}",
  "Chercher un nom, une commune, un numéro…": "Zoek een naam, gemeente of nummer…",
  Tous: "Alle",
  "À appeler": "Te bellen",
  Fait: "Gedaan",
  "À rappeler": "Terugbellen",
  Injoignable: "Onbereikbaar",
  Écarté: "Terzijde",
  "N°": "Nr.",
  Praticien: "Beoefenaar",
  Commune: "Gemeente",
  Téléphone: "Telefoon",
  État: "Status",
  "Appelé le": "Gebeld op",
  doublon: "dubbel",
  "Même numéro que {nom}": "Zelfde nummer als {nom}",
  "Même numéro que « {nom} » — ne pas appeler deux fois le même cabinet.":
    "Zelfde nummer als « {nom} » — bel dezelfde praktijk geen twee keer.",
  "Retirer de la liste": "Uit de lijst halen",
  "Aucun praticien ne correspond.": "Geen enkele beoefenaar komt overeen.",
  "Aucun praticien ne correspond à ce filtre.": "Geen enkele beoefenaar komt overeen met die filter.",
  "Ajouter une autre liste": "Nog een lijst toevoegen",
  "Vider la liste d'appel": "Belijst leegmaken",
  "Aucune liste d'appel chargée. Importe ton fichier de praticiens : province, nom et téléphone seront déjà remplis à chaque appel.":
    "Nog geen belijst geladen. Importeer je bestand met beoefenaars: provincie, naam en telefoon staan dan bij elke oproep al ingevuld.",
  "Charger une liste d'appel": "Een belijst laden",
  copier: "kopiëren",
  Copier: "Kopiëren",
  "Copier le numéro": "Nummer kopiëren",
  "Numéro copié : {numero}": "Nummer gekopieerd: {numero}",
  "Copie refusée par le navigateur.": "De browser weigerde het kopiëren.",

  /* --- formulaire d'appel --- */
  "Suite à donner": "Wat volgt",
  "Par défaut « Fait ». À changer si le cabinet est injoignable ou s'il faut rappeler.":
    "Standaard « Gedaan ». Pas aan als de praktijk onbereikbaar is of als je moet terugbellen.",
  "Rien n'a encore été encodé : aucune ligne ne partira dans le fichier Excel, le praticien est simplement marqué dans la liste.":
    "Er is nog niets gecodeerd: er gaat geen rij naar het Excel-bestand, de beoefenaar wordt enkel in de lijst gemarkeerd.",
  "Marquer « {etat} » et passer au suivant": "« {etat} » markeren en naar de volgende",
  "{fiche} : {etat}. Au suivant : {nom}.": "{fiche}: {etat}. Volgende: {nom}.",
  "{fiche} : {etat}.": "{fiche}: {etat}.",
  "proposé par {nom}": "voorgesteld door {nom}",
  "+ {n} dentiste Y ajouté": "+ {n} tandarts Y toegevoegd",
  "+ {n} dentistes Y ajoutés": "+ {n} tandartsen Y toegevoegd",
  "Un autre dentiste vous a été proposé : encode-le avec le bouton « Enregistrer et encoder le dentiste Y » en bas de page. Il rejoindra ta liste, marqué « dentiste Y ».":
    "Er werd een andere tandarts voorgesteld: codeer die met de knop « Bewaren en tandarts Y coderen » onderaan. Hij komt in je lijst, gemarkeerd als « tandarts Y ».",
  "Prochain praticien à appeler": "Volgende beoefenaar om te bellen",
  "Ouvrir sa fiche": "Fiche openen",
  "Le dentiste": "De tandarts",
  "Nom du dentiste": "Naam van de tandarts",
  "Nom tel qu'il figure dans le fichier": "Naam zoals in het bestand",
  Appeler: "Bellen",
  "Pas de numéro encodé": "Geen nummer ingevuld",
  "Colonne obligatoire du fichier de réponses.": "Verplichte kolom van de antwoordtabel.",
  Quand: "Wanneer",
  "Heure de l'appel": "Uur van de oproep",
  Maintenant: "Nu",
  "Questions posées par le cabinet": "Vragen van de praktijk",
  "À rappeler le lendemain avec le profil « intervention majorée ». La fiche apparaîtra dans l'onglet Suivi.":
    "De dag nadien terugbellen met het profiel « verhoogde tegemoetkoming ». De fiche verschijnt onder Opvolging.",
  "Résultat de l'appel": "Resultaat van de oproep",
  Préciser: "Preciseren",
  "Ce que le cabinet a répondu": "Wat de praktijk antwoordde",
  "Si oui : encoder aussi ce dentiste Y (bouton en bas de page).":
    "Zo ja: codeer ook die tandarts Y (knop onderaan).",
  "Le chiffre seul, même approximatif.": "Enkel het cijfer, ook bij benadering.",
  "ex. 45": "bv. 45",
  "Si le premier rendez-vous est déjà au tarif officiel : oui.":
    "Is de eerste afspraak al aan het officiële tarief: ja.",
  "Hygiéniste bucco-dentaire": "Mondhygiënist",
  "Ce que tu veux retenir de l'appel": "Wat je van de oproep wil onthouden",
  "Afficher toutes les colonnes, même celles qui ne s'appliquent pas":
    "Alle kolommen tonen, ook die niet van toepassing zijn",
  "Encore vide : {champs}. Laisse vide si tu n'es pas sûr — c'est ce que demande le scénario.":
    "Nog leeg: {champs}. Laat leeg als je niet zeker bent — dat vraagt het scenario.",
  "Pratique de groupe": "Groepspraktijk",
  "Le cabinet a proposé un autre dentiste de la même pratique ? Enregistre d'abord cette fiche, puis encode le dentiste Y : il sera exporté juste en dessous, surligné.":
    "Stelde de praktijk een andere tandarts van dezelfde praktijk voor? Bewaar eerst deze fiche en codeer dan tandarts Y: die wordt er meteen onder geëxporteerd, gemarkeerd.",
  "Enregistrer et encoder le dentiste Y": "Bewaren en tandarts Y coderen",
  "Enregistrer et passer au suivant": "Bewaren en naar de volgende",
  "Mettre à jour l'appel": "Oproep bijwerken",
  "Scénario C — dentiste Y.": "Scenario C — tandarts Y.",
  "Cette fiche est rattachée à {nom} : à l'export, elle sera placée juste après lui et surlignée en jaune.":
    "Deze fiche hoort bij {nom}: bij de export komt ze er meteen achter, in het geel gemarkeerd.",
  "le dentiste X": "tandarts X",
  "Ce numéro a déjà été appelé ({nom}{quand}). Le scénario demande de ne pas appeler deux fois le même cabinet.":
    "Dat nummer werd al gebeld ({nom}{quand}). Het scenario vraagt dezelfde praktijk geen twee keer te bellen.",
  " le {date}": " op {date}",
  Ouverture: "Openingszin",
  "Réponses types": "Standaardantwoorden",
  "Masquer les réponses types": "Standaardantwoorden verbergen",
  "Réponses aux questions du secrétariat": "Antwoorden op de vragen van het secretariaat",
  "Si le secrétariat pose une question": "Als het secretariaat een vraag stelt",
  "Consignes de la mission": "Richtlijnen van de opdracht",
  Ensuite: "Daarna",
  "+ {n} autres dans la liste": "+ {n} andere in de lijst",
  "Indique au moins le nom du dentiste avant d'enregistrer.": "Vul minstens de naam van de tandarts in voor je bewaart.",
  "Appel enregistré.": "Oproep bewaard.",
  "Appel enregistré. Au suivant : {nom}.": "Oproep bewaard. Volgende: {nom}.",
  "Encode maintenant le dentiste Y proposé par le cabinet.": "Codeer nu tandarts Y die de praktijk voorstelde.",

  /* --- journée --- */
  "Chercher dans les appels…": "Zoek in de oproepen…",
  Heure: "Uur",
  Statut: "Statuut",
  Résultat: "Resultaat",
  "1er RDV": "1e afspraak",
  Tarif: "Tarief",
  Prix: "Prijs",
  "Sans date": "Zonder datum",
  "Sans nom": "Zonder naam",
  "{n} appel": "{n} oproep",
  "{n} appels": "{n} oproepen",
  "{n} appel encodé": "{n} oproep gecodeerd",
  "{n} appels encodés": "{n} oproepen gecodeerd",
  "dentiste Y": "tandarts Y",
  "à rappeler": "terugbellen",
  "RDV le": "Afspraak op",
  "Pas de rendez-vous": "Geen afspraak",
  "Résultat non renseigné": "Resultaat niet ingevuld",
  "rendez-vous": "afspraak",
  refus: "geweigerd",
  "Ajouter le dentiste Y": "Tandarts Y toevoegen",
  "Encoder le dentiste Y de la même pratique": "Tandarts Y van dezelfde praktijk coderen",
  "Supprimer cet appel": "Deze oproep verwijderen",
  "Supprimer définitivement cet appel ?": "Deze oproep definitief verwijderen?",
  "Appel supprimé.": "Oproep verwijderd.",
  "Aucun appel enregistré pour l'instant. Commence par l'onglet « Liste » ou « Appel ».":
    "Nog geen oproep bewaard. Begin bij het tabblad « Lijst » of « Oproep ».",

  /* --- suivi --- */
  "Rappels avec le profil « intervention majorée »": "Terugbellen met het profiel « verhoogde tegemoetkoming »",
  "Le scénario demande de rappeler le lendemain, avec une voix d'homme et l'autre profil, les cabinets qui ont demandé le numéro de registre national ou parlé d'intervention majorée. Il suffit de noter si un rendez-vous a été obtenu, et la date.":
    "Het scenario vraagt om de dag nadien terug te bellen, met een mannenstem en het andere profiel, naar de praktijken die het rijksregisternummer vroegen of over de verhoogde tegemoetkoming begonnen. Noteer enkel of je een afspraak kreeg, en de datum.",
  "Aucun cabinet à rappeler pour l'instant.": "Voorlopig geen praktijk om terug te bellen.",
  "Appelé le {date} {heure}": "Gebeld op {date} {heure}",
  "intervention majorée": "verhoogde tegemoetkoming",
  "registre national": "rijksregister",
  Rappeler: "Terugbellen",
  "Date du rappel": "Datum van het terugbellen",
  "Date du rendez-vous obtenu": "Datum van de verkregen afspraak",
  "Rendez-vous obtenu avec ce profil ?": "Afspraak gekregen met dit profiel?",
  "Marquer le rappel comme fait": "Terugbellen als gedaan markeren",
  "{n} rappel déjà fait": "{n} keer al teruggebeld",
  "{n} rappels déjà faits": "{n} keer al teruggebeld",
  "RDV le {date}": "Afspraak op {date}",
  "pas de RDV": "geen afspraak",
  rouvrir: "heropenen",
  "Télécharger les rendez-vous (.xlsx)": "Afspraken downloaden (.xlsx)",
  "Rendez-vous": "Afspraken",
  "À annuler à partir du": "Te annuleren vanaf",
  "Où en est l'annulation": "Stand van de annulering",
  "Rendez-vous pris le": "Afspraak vastgelegd op",
  "Tarif annoncé": "Aangekondigd tarief",
  "Prix (€)": "Prijs (€)",
  "Appel du": "Oproep van",
  "À annuler": "Te annuleren",
  "À annuler maintenant": "Nu te annuleren",
  "Annulé le {date}": "Geannuleerd op {date}",
  "Annulé par le cabinet le {date}": "Door de praktijk geannuleerd op {date}",
  "Rendez-vous à annuler": "Afspraken om te annuleren",
  "Rappels — profil habituel": "Terugbellen — gewoon profiel",
  "Les cabinets marqués « À rappeler » : personne n'a décroché, ou on t'a demandé de rappeler plus tard. Rien à changer au scénario, c'est le même appel à refaire.":
    "De praktijken met « Terugbellen »: niemand nam op, of ze vroegen je later terug te bellen. Er verandert niets aan het scenario, het is dezelfde oproep die je opnieuw doet.",
  "Dernier essai le {date} {heure}": "Laatste poging op {date} {heure}",
  "Pas encore d'appel encodé": "Nog geen oproep gecodeerd",
  "Encoder l'appel": "De oproep coderen",
  "Pas de numéro": "Geen nummer",
  "Aucun cabinet à rappeler avec l'autre profil.": "Geen enkele praktijk terug te bellen met het andere profiel.",
  "Un rendez-vous est déjà placé ici, à annuler plus bas.":
    "Hier staat al een afspraak, hieronder te annuleren.",
  "Aucun rendez-vous placé pour l'instant.": "Voorlopig geen enkele afspraak vastgelegd.",
  "{total} rendez-vous placés depuis le début de la mission, dont {reste} encore à annuler.":
    "{total} afspraken vastgelegd sinds het begin van de opdracht, waarvan er nog {reste} te annuleren zijn.",
  "à rappeler — intervention majorée": "terug te bellen — verhoogde tegemoetkoming",
  "Rendez-vous le": "Afspraak op",
  "Rappel « intervention majorée »": "Terugbellen « verhoogde tegemoetkoming »",
  "À annuler seulement après 4 jours ouvrables : Test-Achats veut voir si le cabinet annule de lui-même. Par téléphone ou par e-mail, sans être identifiable.":
    "Pas annuleren na 4 werkdagen: Testaankoop wil zien of de praktijk zelf annuleert. Per telefoon of e-mail, zonder herkenbaar te zijn.",
  "À annuler à partir du": "Te annuleren vanaf",
  "J'ai annulé aujourd'hui": "Ik heb vandaag geannuleerd",
  "J'ai vérifié aujourd'hui": "Ik heb het vandaag gecontroleerd",
  "Le cabinet a annulé lui-même": "De praktijk annuleerde zelf",
  "en retard de {n} j": "{n} d te laat",
  "aujourd'hui": "vandaag",
  demain: "morgen",
  "dans {n} j": "over {n} d",
  "Registre national — contrôle hebdomadaire": "Rijksregister — wekelijkse controle",
  "Vérifier chaque semaine si un dentiste a consulté ton dossier, et transmettre l'information. Lecteur de carte et code PIN nécessaires.":
    "Controleer elke week of een tandarts je dossier heeft geraadpleegd, en geef dat door. Kaartlezer en pincode nodig.",
  "Ouvrir « Mon dossier » sur ibz.rrn.fgov.be": "« Mijn dossier » openen op ibz.rrn.fgov.be",
  "Dernier contrôle : {date}": "Laatste controle: {date}",
  "Aucun contrôle noté.": "Nog geen controle genoteerd.",

  /* --- import --- */
  "Un fichier .xlsx ou .csv de praticiens, ou des lignes copiées depuis Excel. Province, nom et téléphone seront ensuite déjà remplis à chaque appel.":
    "Een .xlsx- of .csv-bestand met beoefenaars, of rijen die je uit Excel kopieert. Provincie, naam en telefoon staan daarna bij elke oproep al ingevuld.",
  "Choisir un fichier": "Een bestand kiezen",
  "Liste .xlsx ou .csv, ou sauvegarde .json": "Lijst .xlsx of .csv, of back-up .json",
  "ou glisse le fichier ici": "of sleep het bestand hierheen",
  "Ou coller": "Of plakken",
  "Colle ici des lignes copiées depuis Excel, ou un code de reprise .json.":
    "Plak hier rijen uit Excel, of een .json-herstelcode.",
  "Lire ce texte": "Deze tekst lezen",
  "Vérifier avant d'importer": "Nakijken voor je importeert",
  "{n} ligne lue": "{n} rij gelezen",
  "{n} lignes lues": "{n} rijen gelezen",
  "{n} colonnes": "{n} kolommen",
  Feuille: "Blad",
  "Ce fichier contient": "Dit bestand bevat",
  "Une liste de praticiens à appeler": "Een lijst met te bellen beoefenaars",
  "Un tableau de réponses déjà rempli (23 colonnes)": "Een al ingevulde antwoordtabel (23 kolommen)",
  "Province si absente du fichier": "Provincie als ze niet in het bestand staat",
  "Statut Inami de cette liste": "Riziv-statuut van deze lijst",
  "— aucune —": "— geen —",
  "— aucun —": "— geen —",
  "— ignorer —": "— negeren —",
  "Correspondance des colonnes": "Overeenkomst van de kolommen",
  "Corrige si une colonne n'a pas été reconnue.": "Verbeter als een kolom niet herkend werd.",
  "Nom du praticien": "Naam van de beoefenaar",
  "N° INAMI": "Riziv-nummer",
  Adresse: "Adres",
  "Code postal": "Postcode",
  Province: "Provincie",
  "Site web": "Website",
  "Autre source": "Andere bron",
  "N° d'ordre": "Volgnummer",
  "Les 23 colonnes du fichier de réponses seront reprises telles quelles comme appels déjà encodés.":
    "De 23 kolommen van de antwoordtabel worden overgenomen als al gecodeerde oproepen.",
  "Importer {n} appel": "{n} oproep importeren",
  "Importer {n} appels": "{n} oproepen importeren",
  "Importer {n} praticien": "{n} beoefenaar importeren",
  "Importer {n} praticiens": "{n} beoefenaars importeren",
  "Ce fichier ne contient aucune ligne exploitable.": "Dit bestand bevat geen bruikbare rij.",
  "Lecture du fichier impossible.": "Het bestand kon niet gelezen worden.",
  "Rien à charger.": "Niets om te laden.",
  "Aucun appel trouvé dans ce tableau.": "Geen enkele oproep gevonden in die tabel.",
  "Aucun praticien trouvé : vérifie la correspondance des colonnes.":
    "Geen enkele beoefenaar gevonden: kijk de overeenkomst van de kolommen na.",
  "{n} praticiens lus. Ouvre l'onglet « Liste » : il n'y a plus qu'à appeler.":
    "{n} beoefenaars gelezen. Open het tabblad « Lijst »: bellen maar.",
  "{n} appels importés.": "{n} oproepen geïmporteerd.",

  /* --- export --- */
  "Remplir le fichier Excel de Test-Achats": "De Excel van Testaankoop invullen",
  "Charge ici le fichier Antwoordtabel que tu dois rendre : l'application y ajoute tes appels en gardant les titres, les listes déroulantes et la mise en forme, puis te rend le fichier complété.":
    "Laad hier de Antwoordtabel die je moet indienen: de app voegt je oproepen toe en behoudt de titels, de keuzelijsten en de opmaak, en geeft je het ingevulde bestand terug.",
  "Le fichier reste en français : les réponses y sont écrites telles que Test-Achats les attend, quelle que soit la langue de l'application.":
    "Het bestand blijft in het Frans: de antwoorden komen erin zoals Testaankoop ze verwacht, welke taal de app ook heeft.",
  "Choisir le fichier Antwoordtabel": "De Antwoordtabel kiezen",
  "Changer de fichier": "Ander bestand kiezen",
  "Fichier .xlsx fourni par Test-Achats": ".xlsx-bestand van Testaankoop",
  "Écrire à partir de la ligne": "Schrijven vanaf rij",
  "Ligne 2 = juste sous les titres. La valeur proposée est la première ligne libre du fichier.":
    "Rij 2 = net onder de titels. De voorgestelde waarde is de eerste vrije rij van het bestand.",
  "Télécharger le fichier rempli ({n} appels)": "Ingevuld bestand downloaden ({n} oproepen)",
  "Écriture en cours…": "Bezig met schrijven…",
  "Modèle chargé : première ligne libre = ligne {n}.": "Sjabloon geladen: eerste vrije rij = rij {n}.",
  "Ce fichier Excel n'a pas pu être lu.": "Dit Excel-bestand kon niet gelezen worden.",
  "{n} appels écrits à partir de la ligne {ligne}. Vérifie le fichier avant de l'envoyer.":
    "{n} oproepen weggeschreven vanaf rij {ligne}. Kijk het bestand na voor je het verstuurt.",
  "Téléchargement refusé par le navigateur — utilise le collage pour Excel.":
    "De browser weigerde de download — gebruik het plakken voor Excel.",
  "Le remplissage a échoué : utilise le collage pour Excel.":
    "Het invullen mislukte: gebruik het plakken voor Excel.",
  "Coller directement dans Excel": "Rechtstreeks in Excel plakken",
  "Le texte ci-dessous contient {n} appels dans l'ordre des 23 colonnes. Copie-le, puis colle-le dans la première cellule vide de la colonne A : Excel répartit les colonnes tout seul.":
    "De tekst hieronder bevat {n} oproepen in de volgorde van de 23 kolommen. Kopieer hem en plak hem in de eerste lege cel van kolom A: Excel verdeelt de kolommen zelf.",
  "Inclure la ligne de titres": "De titelrij meenemen",
  "Copier pour Excel": "Kopiëren voor Excel",
  "Copié. Colle dans la première cellule vide de la colonne A.":
    "Gekopieerd. Plak in de eerste lege cel van kolom A.",
  "Copie automatique refusée — sélectionne le texte ci-dessous à la main.":
    "Automatisch kopiëren geweigerd — selecteer de tekst hieronder met de hand.",
  "Autres fichiers": "Andere bestanden",
  "Classeur .xlsx neuf": "Nieuw .xlsx-bestand",
  "Fichier .csv": ".csv-bestand",
  "Suivi : rappels et annulations": "Opvolging: terugbellen en annuleren",
  "Changer d'appareil": "Van toestel wisselen",
  "Tout est transféré : la liste d'appel, les appels encodés et le suivi. Le fichier .json est le moyen le plus sûr ; le code ci-dessous fait la même chose par copier-coller quand le fichier ne passe pas.":
    "Alles gaat mee: de belijst, de gecodeerde oproepen en de opvolging. Het .json-bestand is de veiligste weg; de code hieronder doet hetzelfde via kopiëren en plakken wanneer het bestand niet doorgeraakt.",
  "1. Emporter le travail": "1. Het werk meenemen",
  "Sur l'appareil que tu quittes.": "Op het toestel dat je verlaat.",
  "Télécharger le fichier .json": "Het .json-bestand downloaden",
  "Copier le code": "De code kopiëren",
  "Code copié ({n} caractères). Colle-le sur l'autre appareil.":
    "Code gekopieerd ({n} tekens). Plak hem op het andere toestel.",
  "Copie automatique refusée : le code est sélectionné, fais Ctrl+C (ou Cmd+C).":
    "Automatisch kopiëren geweigerd: de code is geselecteerd, druk op Ctrl+C (of Cmd+C).",
  "{n} caractères — le code doit être collé en entier, jusqu'à l'accolade finale.":
    "{n} tekens — de code moet volledig geplakt worden, tot en met de slotaccolade.",
  "2. Reprendre le travail ici": "2. Het werk hier hervatten",
  "Sur l'appareil où tu reprends. Le fichier .json se charge, lui, par « Charger une liste d'appel ».":
    "Op het toestel waar je hervat. Het .json-bestand laad je via « Een belijst laden ».",
  "Colle ici le code copié sur l'autre appareil": "Plak hier de code die je op het andere toestel kopieerde",
  "Charger ce code": "Deze code laden",
  "Ce code de reprise est incomplet : il en manque la fin ({n} caractères reçus). Copie-le en entier avec le bouton « Copier le code », ou passe par le fichier .json.":
    "Die herstelcode is onvolledig: het einde ontbreekt ({n} tekens ontvangen). Kopieer hem volledig met de knop « De code kopiëren », of gebruik het .json-bestand.",
  "Ce code de reprise est illisible ({n} caractères reçus) : recopie-le avec le bouton « Copier le code », ou passe par le fichier .json.":
    "Die herstelcode is onleesbaar ({n} tekens ontvangen): kopieer hem opnieuw met de knop « De code kopiëren », of gebruik het .json-bestand.",
  "Ce texte n'est pas un code de reprise : il doit commencer par une accolade « { ».":
    "Die tekst is geen herstelcode: hij moet met een accolade « { » beginnen.",
  "Sauvegarde : {p} praticiens et {c} appels.": "Back-up: {p} beoefenaars en {c} oproepen.",
  "OK = remplacer ce qu'il y a sur cet appareil": "OK = vervangen wat op dit toestel staat",
  "Annuler = compléter sans rien effacer": "Annuleren = aanvullen zonder iets te wissen",
  "Sauvegarde chargée.": "Back-up geladen.",
  "Sauvegarde ajoutée à ce qui existait déjà.": "Back-up toegevoegd aan wat er al stond.",
  "Cette sauvegarde ne contient ni liste d'appel ni appel.": "Die back-up bevat geen belijst en geen oproep.",
  "Après le transfert": "Na de overdracht",
  "À faire seulement une fois les lignes collées et le fichier Excel enregistré.":
    "Pas doen zodra de rijen geplakt zijn en de Excel bewaard is.",
  "Vider les appels encodés": "Gecodeerde oproepen wissen",
  "Vider les appels encodés ? À faire seulement après avoir rempli le fichier Excel.":
    "Gecodeerde oproepen wissen? Pas doen nadat de Excel ingevuld is.",
  "Appels vidés.": "Oproepen gewist.",
  "Tout effacer (liste comprise)": "Alles wissen (ook de lijst)",
  "Tout effacer : liste d'appel, appels et suivi. Cette action est définitive.":
    "Alles wissen: belijst, oproepen en opvolging. Dat is definitief.",
  "Application remise à zéro.": "App teruggezet op nul.",
  "Vider la liste d'appel ? Les appels déjà encodés sont conservés.":
    "De belijst leegmaken? De al gecodeerde oproepen blijven bewaard.",
  "Liste d'appel vidée.": "Belijst leeggemaakt.",
  "Aucun appel encodé pour l'instant : les exports seront vides.":
    "Nog geen oproep gecodeerd: de exports zullen leeg zijn.",
  "Rempli automatiquement — corrige si besoin.": "Automatisch ingevuld — pas aan indien nodig.",

  /* --- raccourcis clavier --- */
  Partout: "Overal",
  "Pendant l'encodage": "Tijdens het coderen",
  "Dans la liste": "In de lijst",
  "Liste des praticiens à appeler": "Lijst met te bellen beoefenaars",
  "Formulaire d'appel": "Oproepformulier",
  "Journée : les appels encodés": "Dag: de gecodeerde oproepen",
  "Données : import, Excel, sauvegarde": "Gegevens: import, Excel, back-up",
  "Aller à la recherche": "Naar het zoekveld",
  "Cette fenêtre": "Dit venster",
  "Fermer la fenêtre ouverte": "Het open venster sluiten",
  "Enregistrer et passer au praticien suivant": "Bewaren en naar de volgende beoefenaar",
  "Idem — le réflexe « enregistrer »": "Idem — de « bewaren »-reflex",
  "Champ ou groupe de réponses suivant": "Volgend veld of volgende antwoordgroep",
  "Choisir une réponse dans le groupe sélectionné": "Een antwoord kiezen in de geselecteerde groep",
  "Valider la réponse sélectionnée": "Het gekozen antwoord bevestigen",
  "Ouvrir le formulaire du praticien sélectionné": "Het formulier van de geselecteerde beoefenaar openen",
  "Praticien suivant": "Volgende beoefenaar",
  "Sur Mac, Ctrl devient ⌘.": "Op een Mac wordt Ctrl ⌘.",
  Entrée: "Enter",
  Espace: "Spatie",
  Échap: "Esc",
};

const EN = {
  /* --- answer-file values (display only) --- */
  oui: "yes",
  non: "no",
  conventionné: "contracted",
  "partiellement conventionné": "partly contracted",
  "non conventionné": "not contracted",
  "avec supplément": "with extra fee",
  "sans supplément": "without extra fee",
  "la personne au téléphone ne le savait pas": "the person on the phone didn't know",
  "ne s'applique pas": "not applicable",
  "je n'ai pas reçu de l'information à ce sujet": "I received no information about this",
  remboursé: "reimbursed",
  "non remboursé": "not reimbursed",
  "pas de nouveaux patients": "no new patients",
  retraite: "retirement",
  autres: "other",

  /* --- answer-file columns --- */
  "Province de l'adresse du dentiste": "Province of the dentist's address",
  Dentiste: "Dentist",
  "Statut Inami": "INAMI status",
  "Date de l'appel": "Date of the call",
  "Nr de téléphone": "Phone number",
  "Le dentiste s'est renseigné sur le droit à l'intervention majorée ?":
    "Did the dentist ask about entitlement to the increased reimbursement?",
  "Le dentiste a demandé votre numéro de registre national ?": "Did the dentist ask for your national register number?",
  "Rendez-vous possible ?": "Appointment possible?",
  "Si pas de rendez-vous : raison": "If no appointment: reason",
  "Orienté vers un autre dentiste de la même pratique de groupe":
    "Referred to another dentist in the same group practice",
  "Orienté vers un dentiste d'un autre cabinet": "Referred to a dentist in another practice",
  "Date du premier rendez-vous proposé": "Date of the first appointment offered",
  "Ce premier rendez-vous est…": "That first appointment is…",
  "Informations reçues sur le prix de la consultation ?": "Did you get information about the price of the consultation?",
  "Prix du premier rendez-vous": "Price of the first appointment",
  "Rendez-vous possible sans supplément ?": "Appointment possible without extra fee?",
  "Date du rendez-vous sans supplément": "Date of the appointment without extra fee",
  "Ce rendez-vous a-t-il lieu dans le même cabinet ?": "Does that appointment take place in the same practice?",
  "Adresse du rendez-vous sans supplément": "Address where the appointment without extra fee takes place",
  "Une consultation chez un hygiéniste a-t-elle été proposée ?": "Was a dental hygienist consultation offered?",
  "Informations reçues sur le remboursement de l'hygiéniste ?":
    "Did you get information about reimbursement for the hygienist?",
  "Cette consultation est…": "That consultation is…",
  Remarques: "Notes",

  /* --- navigation --- */
  "Appels dentistes": "Dentist calls",
  "Mystery shopping · Test-Achats": "Mystery shopping · Test-Achats",
  Liste: "List",
  Appel: "Call",
  Journée: "Day",
  Suivi: "Follow-up",
  Données: "Data",
  "Qui reste à appeler": "Who is left to call",
  "Encoder l'appel en cours": "Record the call in progress",
  "Ce qui est déjà encodé": "What is already recorded",
  "Rappels et annulations": "Call-backs and cancellations",
  "Import, Excel, sauvegarde": "Import, Excel, backup",
  Langue: "Language",
  "Chargement…": "Loading…",
  Fermer: "Close",
  Annuler: "Cancel",
  Modifier: "Edit",
  Replier: "Collapse",
  Supprimer: "Delete",
  Encoder: "Record",
  Revoir: "Review",
  "Revoir l'appel": "Review the call",
  "Plus d'options": "More options",
  Scénario: "Script",
  "Scénario de la mission": "Mission script",
  "Raccourcis clavier": "Keyboard shortcuts",
  "Les réponses partent en français dans le fichier Excel, quelle que soit la langue choisie.":
    "Answers always go into the Excel file in French, whichever language you pick.",

  /* --- call list --- */
  "{faits} / {total} appelés": "{faits} / {total} called",
  "{n} restants": "{n} left",
  "{n} à appeler": "{n} to call",
  "Appeler le suivant : {nom}": "Call the next one: {nom}",
  "Chercher un nom, une commune, un numéro…": "Search a name, town or number…",
  Tous: "All",
  "À appeler": "To call",
  Fait: "Done",
  "À rappeler": "Call back",
  Injoignable: "Unreachable",
  Écarté: "Set aside",
  "N°": "No.",
  Praticien: "Practitioner",
  Commune: "Town",
  Téléphone: "Phone",
  État: "Status",
  "Appelé le": "Called on",
  doublon: "duplicate",
  "Même numéro que {nom}": "Same number as {nom}",
  "Même numéro que « {nom} » — ne pas appeler deux fois le même cabinet.":
    "Same number as “{nom}” — don't call the same practice twice.",
  "Retirer de la liste": "Remove from the list",
  "Aucun praticien ne correspond.": "No practitioner matches.",
  "Aucun praticien ne correspond à ce filtre.": "No practitioner matches this filter.",
  "Ajouter une autre liste": "Add another list",
  "Vider la liste d'appel": "Clear the call list",
  "Aucune liste d'appel chargée. Importe ton fichier de praticiens : province, nom et téléphone seront déjà remplis à chaque appel.":
    "No call list loaded yet. Import your practitioner file: province, name and phone will already be filled in for every call.",
  "Charger une liste d'appel": "Load a call list",
  copier: "copy",
  Copier: "Copy",
  "Copier le numéro": "Copy the number",
  "Numéro copié : {numero}": "Number copied: {numero}",
  "Copie refusée par le navigateur.": "The browser refused to copy.",

  /* --- call form --- */
  "Suite à donner": "What next",
  "Par défaut « Fait ». À changer si le cabinet est injoignable ou s'il faut rappeler.":
    "“Done” by default. Change it if the practice is unreachable or needs calling back.",
  "Rien n'a encore été encodé : aucune ligne ne partira dans le fichier Excel, le praticien est simplement marqué dans la liste.":
    "Nothing recorded yet: no row will go into the Excel file, the practitioner is just marked in the list.",
  "Marquer « {etat} » et passer au suivant": "Mark “{etat}” and go to the next one",
  "{fiche} : {etat}. Au suivant : {nom}.": "{fiche}: {etat}. Next: {nom}.",
  "{fiche} : {etat}.": "{fiche}: {etat}.",
  "proposé par {nom}": "offered by {nom}",
  "+ {n} dentiste Y ajouté": "+ {n} dentist Y added",
  "+ {n} dentistes Y ajoutés": "+ {n} dentists Y added",
  "Un autre dentiste vous a été proposé : encode-le avec le bouton « Enregistrer et encoder le dentiste Y » en bas de page. Il rejoindra ta liste, marqué « dentiste Y ».":
    "Another dentist was offered: record them with the “Save and record dentist Y” button at the bottom. They will join your list, marked “dentist Y”.",
  "Prochain praticien à appeler": "Next practitioner to call",
  "Ouvrir sa fiche": "Open their record",
  "Le dentiste": "The dentist",
  "Nom du dentiste": "Dentist's name",
  "Nom tel qu'il figure dans le fichier": "Name as written in the file",
  Appeler: "Call",
  "Pas de numéro encodé": "No number recorded",
  "Colonne obligatoire du fichier de réponses.": "Required column of the answer file.",
  Quand: "When",
  "Heure de l'appel": "Time of the call",
  Maintenant: "Now",
  "Questions posées par le cabinet": "Questions asked by the practice",
  "À rappeler le lendemain avec le profil « intervention majorée ». La fiche apparaîtra dans l'onglet Suivi.":
    "Call back the next day with the “increased reimbursement” profile. The record will show up under Follow-up.",
  "Résultat de l'appel": "Outcome of the call",
  Préciser: "Specify",
  "Ce que le cabinet a répondu": "What the practice answered",
  "Si oui : encoder aussi ce dentiste Y (bouton en bas de page).":
    "If yes: record that dentist Y as well (button at the bottom).",
  "Le chiffre seul, même approximatif.": "The figure only, even approximate.",
  "ex. 45": "e.g. 45",
  "Si le premier rendez-vous est déjà au tarif officiel : oui.":
    "If the first appointment is already at the official rate: yes.",
  "Hygiéniste bucco-dentaire": "Dental hygienist",
  "Ce que tu veux retenir de l'appel": "Anything worth remembering about the call",
  "Afficher toutes les colonnes, même celles qui ne s'appliquent pas":
    "Show every column, even those that don't apply",
  "Encore vide : {champs}. Laisse vide si tu n'es pas sûr — c'est ce que demande le scénario.":
    "Still empty: {champs}. Leave blank if you're not sure — that's what the script asks.",
  "Pratique de groupe": "Group practice",
  "Le cabinet a proposé un autre dentiste de la même pratique ? Enregistre d'abord cette fiche, puis encode le dentiste Y : il sera exporté juste en dessous, surligné.":
    "Did the practice offer another dentist from the same group? Save this record first, then record dentist Y: they will be exported right below, highlighted.",
  "Enregistrer et encoder le dentiste Y": "Save and record dentist Y",
  "Enregistrer et passer au suivant": "Save and go to the next one",
  "Mettre à jour l'appel": "Update the call",
  "Scénario C — dentiste Y.": "Scenario C — dentist Y.",
  "Cette fiche est rattachée à {nom} : à l'export, elle sera placée juste après lui et surlignée en jaune.":
    "This record is attached to {nom}: on export it will sit right after them, highlighted in yellow.",
  "le dentiste X": "dentist X",
  "Ce numéro a déjà été appelé ({nom}{quand}). Le scénario demande de ne pas appeler deux fois le même cabinet.":
    "This number has already been called ({nom}{quand}). The script says not to call the same practice twice.",
  " le {date}": " on {date}",
  Ouverture: "Opening line",
  "Réponses types": "Standard answers",
  "Masquer les réponses types": "Hide the standard answers",
  "Réponses aux questions du secrétariat": "Answers to the receptionist's questions",
  "Si le secrétariat pose une question": "If the receptionist asks a question",
  "Consignes de la mission": "Mission instructions",
  Ensuite: "Up next",
  "+ {n} autres dans la liste": "+ {n} more in the list",
  "Indique au moins le nom du dentiste avant d'enregistrer.": "Enter at least the dentist's name before saving.",
  "Appel enregistré.": "Call saved.",
  "Appel enregistré. Au suivant : {nom}.": "Call saved. Next: {nom}.",
  "Encode maintenant le dentiste Y proposé par le cabinet.": "Now record dentist Y offered by the practice.",

  /* --- day --- */
  "Chercher dans les appels…": "Search the calls…",
  Heure: "Time",
  Statut: "Status",
  Résultat: "Outcome",
  "1er RDV": "1st appt.",
  Tarif: "Rate",
  Prix: "Price",
  "Sans date": "No date",
  "Sans nom": "No name",
  "{n} appel": "{n} call",
  "{n} appels": "{n} calls",
  "{n} appel encodé": "{n} call recorded",
  "{n} appels encodés": "{n} calls recorded",
  "dentiste Y": "dentist Y",
  "à rappeler": "call back",
  "RDV le": "Appointment on",
  "Pas de rendez-vous": "No appointment",
  "Résultat non renseigné": "Outcome not filled in",
  "rendez-vous": "appointment",
  refus: "refused",
  "Ajouter le dentiste Y": "Add dentist Y",
  "Encoder le dentiste Y de la même pratique": "Record dentist Y from the same practice",
  "Supprimer cet appel": "Delete this call",
  "Supprimer définitivement cet appel ?": "Delete this call for good?",
  "Appel supprimé.": "Call deleted.",
  "Aucun appel enregistré pour l'instant. Commence par l'onglet « Liste » ou « Appel ».":
    "No call saved yet. Start with the “List” or “Call” tab.",

  /* --- follow-up --- */
  "Rappels avec le profil « intervention majorée »": "Call-backs with the “increased reimbursement” profile",
  "Le scénario demande de rappeler le lendemain, avec une voix d'homme et l'autre profil, les cabinets qui ont demandé le numéro de registre national ou parlé d'intervention majorée. Il suffit de noter si un rendez-vous a été obtenu, et la date.":
    "The script asks you to call back the next day, with a male voice and the other profile, every practice that asked for the national register number or raised the increased reimbursement. Just record whether you got an appointment, and the date.",
  "Aucun cabinet à rappeler pour l'instant.": "No practice to call back for now.",
  "Appelé le {date} {heure}": "Called on {date} {heure}",
  "intervention majorée": "increased reimbursement",
  "registre national": "national register",
  Rappeler: "Call back",
  "Date du rappel": "Date of the call-back",
  "Date du rendez-vous obtenu": "Date of the appointment obtained",
  "Rendez-vous obtenu avec ce profil ?": "Appointment obtained with this profile?",
  "Marquer le rappel comme fait": "Mark the call-back as done",
  "{n} rappel déjà fait": "{n} call-back already done",
  "{n} rappels déjà faits": "{n} call-backs already done",
  "RDV le {date}": "Appointment on {date}",
  "pas de RDV": "no appointment",
  rouvrir: "reopen",
  "Télécharger les rendez-vous (.xlsx)": "Download the appointments (.xlsx)",
  "Rendez-vous": "Appointments",
  "À annuler à partir du": "To cancel from",
  "Où en est l'annulation": "Cancellation status",
  "Rendez-vous pris le": "Appointment booked for",
  "Tarif annoncé": "Rate announced",
  "Prix (€)": "Price (€)",
  "Appel du": "Call of",
  "À annuler": "To cancel",
  "À annuler maintenant": "Cancel now",
  "Annulé le {date}": "Cancelled on {date}",
  "Annulé par le cabinet le {date}": "Cancelled by the practice on {date}",
  "Rendez-vous à annuler": "Appointments to cancel",
  "Rappels — profil habituel": "Call-backs — usual profile",
  "Les cabinets marqués « À rappeler » : personne n'a décroché, ou on t'a demandé de rappeler plus tard. Rien à changer au scénario, c'est le même appel à refaire.":
    "The practices marked “To call back”: nobody picked up, or they asked you to call again later. Nothing changes in the scenario — it is the same call, made again.",
  "Dernier essai le {date} {heure}": "Last attempt on {date} {heure}",
  "Pas encore d'appel encodé": "No call recorded yet",
  "Encoder l'appel": "Record the call",
  "Pas de numéro": "No number",
  "Aucun cabinet à rappeler avec l'autre profil.": "No practice to call back with the other profile.",
  "Un rendez-vous est déjà placé ici, à annuler plus bas.":
    "An appointment is already booked here — cancel it below.",
  "Aucun rendez-vous placé pour l'instant.": "No appointment booked yet.",
  "{total} rendez-vous placés depuis le début de la mission, dont {reste} encore à annuler.":
    "{total} appointments booked since the mission started, {reste} of them still to cancel.",
  "à rappeler — intervention majorée": "to call back — increased allowance",
  "Rendez-vous le": "Appointment on",
  "Rappel « intervention majorée »": "Call-back “increased allowance”",
  "À annuler seulement après 4 jours ouvrables : Test-Achats veut voir si le cabinet annule de lui-même. Par téléphone ou par e-mail, sans être identifiable.":
    "Only cancel after 4 working days: Test-Achats wants to see whether the practice cancels by itself. By phone or e-mail, without being identifiable.",
  "À annuler à partir du": "To cancel from",
  "J'ai annulé aujourd'hui": "I cancelled today",
  "J'ai vérifié aujourd'hui": "I checked today",
  "Le cabinet a annulé lui-même": "The practice cancelled by itself",
  "en retard de {n} j": "{n} d overdue",
  "aujourd'hui": "today",
  demain: "tomorrow",
  "dans {n} j": "in {n} d",
  "Registre national — contrôle hebdomadaire": "National register — weekly check",
  "Vérifier chaque semaine si un dentiste a consulté ton dossier, et transmettre l'information. Lecteur de carte et code PIN nécessaires.":
    "Check every week whether a dentist has looked at your file, and pass the information on. Card reader and PIN required.",
  "Ouvrir « Mon dossier » sur ibz.rrn.fgov.be": "Open “My file” on ibz.rrn.fgov.be",
  "Dernier contrôle : {date}": "Last check: {date}",
  "Aucun contrôle noté.": "No check recorded yet.",

  /* --- import --- */
  "Un fichier .xlsx ou .csv de praticiens, ou des lignes copiées depuis Excel. Province, nom et téléphone seront ensuite déjà remplis à chaque appel.":
    "An .xlsx or .csv file of practitioners, or rows copied from Excel. Province, name and phone will then already be filled in for every call.",
  "Choisir un fichier": "Choose a file",
  "Liste .xlsx ou .csv, ou sauvegarde .json": "List .xlsx or .csv, or .json backup",
  "ou glisse le fichier ici": "or drop the file here",
  "Ou coller": "Or paste",
  "Colle ici des lignes copiées depuis Excel, ou un code de reprise .json.":
    "Paste rows copied from Excel here, or a .json restore code.",
  "Lire ce texte": "Read this text",
  "Vérifier avant d'importer": "Check before importing",
  "{n} ligne lue": "{n} row read",
  "{n} lignes lues": "{n} rows read",
  "{n} colonnes": "{n} columns",
  Feuille: "Sheet",
  "Ce fichier contient": "This file contains",
  "Une liste de praticiens à appeler": "A list of practitioners to call",
  "Un tableau de réponses déjà rempli (23 colonnes)": "An answer table already filled in (23 columns)",
  "Province si absente du fichier": "Province if missing from the file",
  "Statut Inami de cette liste": "INAMI status of this list",
  "— aucune —": "— none —",
  "— aucun —": "— none —",
  "— ignorer —": "— ignore —",
  "Correspondance des colonnes": "Column mapping",
  "Corrige si une colonne n'a pas été reconnue.": "Fix it if a column wasn't recognised.",
  "Nom du praticien": "Practitioner's name",
  "N° INAMI": "INAMI number",
  Adresse: "Address",
  "Code postal": "Postcode",
  Province: "Province",
  "Site web": "Website",
  "Autre source": "Other source",
  "N° d'ordre": "Order number",
  "Les 23 colonnes du fichier de réponses seront reprises telles quelles comme appels déjà encodés.":
    "The 23 columns of the answer file will be taken over as already recorded calls.",
  "Importer {n} appel": "Import {n} call",
  "Importer {n} appels": "Import {n} calls",
  "Importer {n} praticien": "Import {n} practitioner",
  "Importer {n} praticiens": "Import {n} practitioners",
  "Ce fichier ne contient aucune ligne exploitable.": "This file contains no usable row.",
  "Lecture du fichier impossible.": "The file could not be read.",
  "Rien à charger.": "Nothing to load.",
  "Aucun appel trouvé dans ce tableau.": "No call found in that table.",
  "Aucun praticien trouvé : vérifie la correspondance des colonnes.":
    "No practitioner found: check the column mapping.",
  "{n} praticiens lus. Ouvre l'onglet « Liste » : il n'y a plus qu'à appeler.":
    "{n} practitioners read. Open the “List” tab: all that's left is calling.",
  "{n} appels importés.": "{n} calls imported.",

  /* --- export --- */
  "Remplir le fichier Excel de Test-Achats": "Fill in the Test-Achats Excel file",
  "Charge ici le fichier Antwoordtabel que tu dois rendre : l'application y ajoute tes appels en gardant les titres, les listes déroulantes et la mise en forme, puis te rend le fichier complété.":
    "Load the Antwoordtabel file you have to hand in: the app adds your calls to it, keeping the headings, the drop-down lists and the formatting, and gives you the completed file back.",
  "Le fichier reste en français : les réponses y sont écrites telles que Test-Achats les attend, quelle que soit la langue de l'application.":
    "The file stays in French: answers are written exactly as Test-Achats expects them, whatever language the app is in.",
  "Choisir le fichier Antwoordtabel": "Choose the Antwoordtabel file",
  "Changer de fichier": "Choose another file",
  "Fichier .xlsx fourni par Test-Achats": ".xlsx file supplied by Test-Achats",
  "Écrire à partir de la ligne": "Write from row",
  "Ligne 2 = juste sous les titres. La valeur proposée est la première ligne libre du fichier.":
    "Row 2 = just below the headings. The suggested value is the first free row in the file.",
  "Télécharger le fichier rempli ({n} appels)": "Download the completed file ({n} calls)",
  "Écriture en cours…": "Writing…",
  "Modèle chargé : première ligne libre = ligne {n}.": "Template loaded: first free row = row {n}.",
  "Ce fichier Excel n'a pas pu être lu.": "This Excel file could not be read.",
  "{n} appels écrits à partir de la ligne {ligne}. Vérifie le fichier avant de l'envoyer.":
    "{n} calls written from row {ligne}. Check the file before sending it.",
  "Téléchargement refusé par le navigateur — utilise le collage pour Excel.":
    "The browser refused the download — use the Excel paste instead.",
  "Le remplissage a échoué : utilise le collage pour Excel.": "Filling in failed: use the Excel paste instead.",
  "Coller directement dans Excel": "Paste straight into Excel",
  "Le texte ci-dessous contient {n} appels dans l'ordre des 23 colonnes. Copie-le, puis colle-le dans la première cellule vide de la colonne A : Excel répartit les colonnes tout seul.":
    "The text below holds {n} calls in the order of the 23 columns. Copy it, then paste it into the first empty cell of column A: Excel splits the columns by itself.",
  "Inclure la ligne de titres": "Include the heading row",
  "Copier pour Excel": "Copy for Excel",
  "Copié. Colle dans la première cellule vide de la colonne A.":
    "Copied. Paste into the first empty cell of column A.",
  "Copie automatique refusée — sélectionne le texte ci-dessous à la main.":
    "Automatic copy refused — select the text below by hand.",
  "Autres fichiers": "Other files",
  "Classeur .xlsx neuf": "New .xlsx workbook",
  "Fichier .csv": ".csv file",
  "Suivi : rappels et annulations": "Follow-up: call-backs and cancellations",
  "Changer d'appareil": "Switch device",
  "Tout est transféré : la liste d'appel, les appels encodés et le suivi. Le fichier .json est le moyen le plus sûr ; le code ci-dessous fait la même chose par copier-coller quand le fichier ne passe pas.":
    "Everything travels: the call list, the recorded calls and the follow-up. The .json file is the safest route; the code below does the same by copy-paste when the file won't go through.",
  "1. Emporter le travail": "1. Take the work with you",
  "Sur l'appareil que tu quittes.": "On the device you are leaving.",
  "Télécharger le fichier .json": "Download the .json file",
  "Copier le code": "Copy the code",
  "Code copié ({n} caractères). Colle-le sur l'autre appareil.":
    "Code copied ({n} characters). Paste it on the other device.",
  "Copie automatique refusée : le code est sélectionné, fais Ctrl+C (ou Cmd+C).":
    "Automatic copy refused: the code is selected, press Ctrl+C (or Cmd+C).",
  "{n} caractères — le code doit être collé en entier, jusqu'à l'accolade finale.":
    "{n} characters — the code must be pasted whole, up to the closing brace.",
  "2. Reprendre le travail ici": "2. Resume the work here",
  "Sur l'appareil où tu reprends. Le fichier .json se charge, lui, par « Charger une liste d'appel ».":
    "On the device where you resume. The .json file itself loads through “Load a call list”.",
  "Colle ici le code copié sur l'autre appareil": "Paste here the code copied on the other device",
  "Charger ce code": "Load this code",
  "Ce code de reprise est incomplet : il en manque la fin ({n} caractères reçus). Copie-le en entier avec le bouton « Copier le code », ou passe par le fichier .json.":
    "That restore code is incomplete: the end is missing ({n} characters received). Copy it whole with the “Copy the code” button, or use the .json file.",
  "Ce code de reprise est illisible ({n} caractères reçus) : recopie-le avec le bouton « Copier le code », ou passe par le fichier .json.":
    "That restore code can't be read ({n} characters received): copy it again with the “Copy the code” button, or use the .json file.",
  "Ce texte n'est pas un code de reprise : il doit commencer par une accolade « { ».":
    "That text is not a restore code: it must start with a “{” brace.",
  "Sauvegarde : {p} praticiens et {c} appels.": "Backup: {p} practitioners and {c} calls.",
  "OK = remplacer ce qu'il y a sur cet appareil": "OK = replace what is on this device",
  "Annuler = compléter sans rien effacer": "Cancel = add to it without erasing anything",
  "Sauvegarde chargée.": "Backup loaded.",
  "Sauvegarde ajoutée à ce qui existait déjà.": "Backup added to what was already there.",
  "Cette sauvegarde ne contient ni liste d'appel ni appel.": "That backup holds neither a call list nor a call.",
  "Après le transfert": "After the transfer",
  "À faire seulement une fois les lignes collées et le fichier Excel enregistré.":
    "Only once the rows are pasted and the Excel file is saved.",
  "Vider les appels encodés": "Clear the recorded calls",
  "Vider les appels encodés ? À faire seulement après avoir rempli le fichier Excel.":
    "Clear the recorded calls? Only after filling in the Excel file.",
  "Appels vidés.": "Calls cleared.",
  "Tout effacer (liste comprise)": "Erase everything (list included)",
  "Tout effacer : liste d'appel, appels et suivi. Cette action est définitive.":
    "Erase everything: call list, calls and follow-up. This cannot be undone.",
  "Application remise à zéro.": "App reset.",
  "Vider la liste d'appel ? Les appels déjà encodés sont conservés.":
    "Clear the call list? The calls already recorded are kept.",
  "Liste d'appel vidée.": "Call list cleared.",
  "Aucun appel encodé pour l'instant : les exports seront vides.":
    "No call recorded yet: the exports will be empty.",
  "Rempli automatiquement — corrige si besoin.": "Filled in automatically — change it if needed.",

  /* --- keyboard shortcuts --- */
  Partout: "Everywhere",
  "Pendant l'encodage": "While recording",
  "Dans la liste": "In the list",
  "Liste des praticiens à appeler": "List of practitioners to call",
  "Formulaire d'appel": "Call form",
  "Journée : les appels encodés": "Day: the recorded calls",
  "Données : import, Excel, sauvegarde": "Data: import, Excel, backup",
  "Aller à la recherche": "Jump to the search box",
  "Cette fenêtre": "This window",
  "Fermer la fenêtre ouverte": "Close the open window",
  "Enregistrer et passer au praticien suivant": "Save and move to the next practitioner",
  "Idem — le réflexe « enregistrer »": "Same — the “save” reflex",
  "Champ ou groupe de réponses suivant": "Next field or answer group",
  "Choisir une réponse dans le groupe sélectionné": "Pick an answer in the selected group",
  "Valider la réponse sélectionnée": "Confirm the selected answer",
  "Ouvrir le formulaire du praticien sélectionné": "Open the selected practitioner's form",
  "Praticien suivant": "Next practitioner",
  "Sur Mac, Ctrl devient ⌘.": "On a Mac, Ctrl becomes ⌘.",
  Entrée: "Enter",
  Espace: "Space",
  Échap: "Esc",
};

export const DICTIONNAIRES = { nl: NL, en: EN };
